name: 'Create a Release'
description: 'Create a release for a tag in your repository'
author: 'GitHub'
inputs:
  token:
    description: >
      Personal access token (PAT) used to create the release.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    required: false
    default: ${{ github.token }}
  tag_name:
    description: 'The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag'
    required: true
  release_name:
    description: 'The name of the release. For example, `Release v1.0.1`'
    required: true
  body:
    description: 'Text describing the contents of the tag.'
    required: false
  draft:
    description: '`true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`'
    required: false
    default: false
  prerelease:
    description: '`true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`'
    required: false
    default: false
outputs:
  id:
    description: 'The ID of the created Release'
  html_url:
    description: 'The URL users can navigate to in order to view the release'
  upload_url:
    description: 'The URL for uploading assets to the release'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
